#アプリケーション情報
app:
  name: KAWAII
  version: 0.0.4
#FANZAカテゴリ情報
keyword:
  - name: 巨乳
    keyword: 巨乳
    moji: 巨
  - name: 貧乳
    keyword: 貧乳
    moji: 貧
  - name: パイパン
    keyword: パイパン
    moji: パ
  - name: パイズリ
    keyword: パイズリ
    moji: パ
  - name: ディルド
    keyword: ディルド
    moji: デ
  - name: 中出し
    keyword: 中出し
    moji: 中
  - name: 潮吹き
    keyword: 潮吹き
    moji: 潮
  - name: 生ハメ
    keyword: 生ハメ
    moji: 生
  - name: ローション
    keyword: ローション
    moji: ロ
  - name: ナンパ
    keyword: ナンパ
    moji: ナ
  - name: クンニ
    keyword: クンニ
    moji: ク